name: CI

on:
  push:
    branches:
      - main
      - dev/**/*
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-steps

      - name: run pre-commit
        if: ${{ !env.ACT }} # Skip during local actions testing
        run: pnpm pre-commit

  chromatic:
    if: ${{ !github.event.act }} # skip during local actions testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Common Setup
        uses: ./.github/actions/common-steps

      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/storybook

      - name: Discord Webhook
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Storybook Link - ${{ steps.chromatic.outputs.storybookUrl }}"
