name: CI

on:
  push:
    branches:
      - main
      - feature/**/*
      - fix/**/*
      - refactor/**/*
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-steps
      - name: Run pre-commit
        if: ${{ !env.ACT }} # Skip during local actions testing
        run: pnpm pre-commit

  chromatic-packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: ui
            dir: packages/ui
          - name: web
            dir: apps/web

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: ./.github/actions/common-steps

      - name: Build UI dependency
        if: matrix.name == 'web'
        run: pnpm ui build

      - name: Run Chromatic (${{ matrix.name }})
        uses: chromaui/action@latest
        with:
          projectToken: ${{ matrix.name == 'ui' && secrets.CHROMATIC_PROJECT_TOKEN_UI || secrets.CHROMATIC_PROJECT_TOKEN_WEB }}
          workingDir: ${{ matrix.dir }}
          buildScriptName: storybook:build

  chromatic-storybook:
    needs: chromatic-packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: ./.github/actions/common-steps

      - run: pnpm ui build

      - name: Run Chromatic (storybook)
        id: chromatic
        uses: chromaui/action@latest
        continue-on-error: true
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/storybook
          buildScriptName: storybook:build
          exitOnceUploaded: true

      - name: Notify Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Storybook Link -${{ steps.chromatic.outputs.storybookUrl }}"
